### ISSUE TITLE
Output of progressive jpgs possible?

### ISSUE THREAD

**Issue by itWilllBeOk** [modxcms/Resizer#13]
Thanks for this great extra.

Would it be possible to have an option for progressive jpgs? That would be a huge plus (since Flash is pretty much dead, last I heard ;)

Thanks again.

**Comment by vierkantemeter** [comment]
:+1:  That's a great idea

**Comment by pyrographics** [comment]
+1

**Comment by itWilllBeOk** [comment]
Pushing this back up again.
As @donShakespeare noticed, the Imagine core is quite outdated in Resizer. It has been upgraded to support interlacing for a while now: https://github.com/avalanche123/Imagine/pull/196
An update here by some knowledgable person would be greatly appreciated :)

**Comment by sepiariver** [comment]
Please see https://sepiariver.com/modx/resizer-update/  the [latest version of Resizer](https://modx.com/extras/package/resizer) should fix this. Imagine 0.7.1 is included.
