### ISSUE TITLE
Watermark not working

### ISSUE THREAD

**Issue by davidpede** [modxcms/Resizer#15]
Hi,

Doc's state that Resizer supports `fltr[]=wmt` but I cannot get this to work:

```
[[+file_url:pthumb=`&w=1600&h=1000&far=0&fltr[]=wmt|Watermark Text|5|C|`]]
```

I have to disable Resizer in the system settings, then work as expected. Is there an issue with my syntax or the extra?

Thanks

**Comment by vierkantemeter** [comment]
Might be related: https://github.com/modxcms/Resizer/issues/6
