### ISSUE TITLE
Error on convert pdf to png

### ISSUE THREAD

**Issue by mukeshcp** [modxcms/Resizer#16]
hi,
  Give error while convert pdf to png by using below command : 
convert -density 300 -depth 8 -quality 85 655382767_1460008284.pdf[0-9] 655382767_1460008284.png

OS : Redhat 64 bit 6.7
ImageMagick : version  6.7.2-7 2015-02-27 Q16
Ghostscript : GPL Ghostscript 8.70 (2009-07-31)
![issueimgmagick](https://cloud.githubusercontent.com/assets/12266888/14849219/66491f58-0c8f-11e6-8887-7cfed09c4d27.png)

Its give below error : 
+++++++++++++++++++++++++++++++++
Error: /ioerror in --showpage--
Operand stack:
   1   true
Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   1862   1   3   %oparray_pop   1861   1   3   %oparray_pop   1845   1   3   %oparray_pop   --nostringval--   --nostringval--   4   1   8   --nostringval--   %for_pos_int_continue   --nostringval--   --nostringval--   1745   0   9   %oparray_pop   --nostringval--   --nostringval--
Dictionary stack:
   --dict:1157/1684(ro)(G)--   --dict:1/20(G)--   --dict:75/200(L)--   --dict:75/200(L)--   --dict:106/127(ro)(G)--   --dict:286/300(ro)(G)--   --dict:22/25(L)--   --dict:4/6(L)--   --dict:27/40(L)--
Current allocation mode is local
Last OS error: 28
GPL Ghostscript 8.70: Unrecoverable error, exit code 1
convert: Postscript delegate failed `655382767_1460008284.pdf': No such file or directory @ error/pdf.c/ReadPDFImage/664.
convert: missing an image filename`655382767_1460008284.png' @ error/convert.c/ConvertImageCommand/3015.
++++++++++++++++++++++++++++++++++

Please help me to fix it.
Also some other pdf files are converted perfactly to png.

Please find attachment of pdf file which are making issue on converting to png using Imagemagick convert command.
[655382767_1460008284.pdf](https://github.com/modxcms/Resizer/files/238435/655382767_1460008284.pdf)

**Comment by sepiariver** [comment]
Please try using phpthumb instead of Resizer (there's a pThumb system setting for this). Resizer does not currently support making thumbnails from PDFs, I believe.
