### ISSUE TITLE
Fatal error: Class 'Reductionist\Reductionist' not found in /home/..../resizer.class.php on line 27

### ISSUE THREAD

**Issue by aw-creative** [modxcms/Resizer#20]
UCannot get resizer to work on server, 

Ubuntu 16.04 php7.1 gd2

**Comment by pixelive** [comment]
Any updates on this one?

**Comment by sdrenth** [comment]
This PR would fix the issue:
https://github.com/modxcms/Resizer/pull/19

Would be nice to see this PR merged!

**Comment by aw-creative** [comment]
My particular issue was resolved by uninstalling the SEO Pro Package.

**Comment by sepiariver** [comment]
https://github.com/modxcms/Resizer/pull/19 was merged.
