### ISSUE TITLE
Shadow in PNG not handled correctly

### ISSUE THREAD

**Issue by travisbotello** [modxcms/Resizer#21]
I am trying to resize the following PNG image:

![screenshot 2018-09-06 18 12 35](https://user-images.githubusercontent.com/1157380/45170579-7c4d8780-b200-11e8-8a44-d92c62bff91a.png)

Using resizer:

![screenshot 2018-09-06 18 13 26](https://user-images.githubusercontent.com/1157380/45170617-8ff8ee00-b200-11e8-9548-5b79c2d85c98.png)

Using phpThumb:

![screenshot 2018-09-06 18 13 59](https://user-images.githubusercontent.com/1157380/45170643-a4d58180-b200-11e8-9160-f27c6c130672.png)

Am I missing an option/setting for resizer here? phpThumb doesn't have any issues.

Thanks in advance!

**Comment by sepiariver** [comment]
Does the [latest version of Resizer](https://modx.com/extras/package/resizer) fix this?

**Comment by travisbotello** [comment]
Can't reproduce it. Seems to be fixed...Thanks!!
